### ISSUE TITLE
CCTV-4K超高清无法播放

### ISSUE THREAD

**Issue by Jinccy** [xiechangan123/CN#1]
感谢您提供的m3u！
我这边测试CCTV-4K超高清无法播放。
其它的link可以正常播放。
地址：安徽合肥移动宽带

**Comment by xiechangan123** [comment]
> 感谢您提供的m3u！ 我这边测试CCTV-4K超高清无法播放。 其它的link可以正常播放。 地址：安徽合肥移动宽带

已更新，个人使用，请勿外传
